### ISSUE TITLE
config.cfg isnt loaded properly

### ISSUE THREAD

**Issue by Caroliiiin** [ItzMuri/ox_inventory-reskin#1]
setr inventory:slots 50

the inventory ingame always has 25 slots (30 with quickslots). no matter what i change.
the config.cfg is properly loaded in the cfg "exec @ox_inventory/config.cfg". the other ox files are loaded after that.

by changing only the build in my original ox_inventory the same problem appears. everything works except the slots.
when changing the build back to the original one, the slots are properly displayed again.

**Comment by ProjectRogueRP** [comment]
This is a bug Im experiencing too!

**Comment by ItzMuri** [comment]
fixed in the last update
