### ISSUE TITLE
acn you update ox inventory version ? as your ver. is not supported at qbox!

### ISSUE THREAD

**Issue by subhampro** [ItzMuri/ox_inventory-reskin#11]
the qbx_core cannot start because of low ver. of inventory and there are many issues over there ! It will be great if you can do the same!

**Comment by subhampro** [comment]
![image](https://github.com/user-attachments/assets/97dc3f3b-5cf8-4633-8b5c-a0b026d9189e)

**Comment by ItzMuri** [comment]
test it now

**Comment by Boom1053** [comment]
needs another update i believe?

**Comment by subhampro** [comment]
Cool
