### ISSUE TITLE
Include HTML/JS source files

### ISSUE THREAD

**Issue by bandgeekndb** [ItzMuri/ox_inventory-reskin#2]
Love the reskin, thanks for sharing!

Our team has made changes to the source files of the UI and so we maintain our own fork of ox_inventory and build the web assets after each update.  I'd love to be able to use this reskin, but without the source files, I can't merge your reskin with our changes to the source files.

If you'd consider including the source files from the web directory, that would be an awesome addition to this repo for anyone who needs those files.

Thanks!

**Comment by ItzMuri** [comment]
added
