### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by DodoDeveloper** [ItzMuri/ox_inventory-reskin#3]
**Describe the bug**
If i have the normal ox inventory in it works but when i put this edit in i can nolonger use the inventory and also dosent show any of the keys in the fivem keybinds section of settings

**Framework**
Latest QB Core

**Resource version**
latest update

**Comment by SkurtReynoldz** [comment]
yea im getting the same thing

**Comment by LYRYCAL** [comment]
If you guys still can't find the problem.
Go to web/build/index.html make sure to edit on index.html must be the same with .js & .css.

**Comment by porcelain-doll** [comment]
Anyone get this to work? My inventory doesn't open and I'm not sure what to do but I really want to use this!
