### ISSUE TITLE
slots bug in left inventory

### ISSUE THREAD

**Issue by faiqhilmy75** [ItzMuri/ox_inventory-reskin#4]
**Describe the bug**
cant change the total slot of left inventory

**Comment by tobybacoon** [comment]
having the same issue

**Comment by faiqhilmy75** [comment]
> issue

check the PR, someone submit a PR and will fix it

**Comment by faiqhilmy75** [comment]
> having the same issue
check the PR, someone submit a PR and will fix the issue
