### ISSUE TITLE
Drop prop is some kind of wheelchair prop not bag or arrow mark like usual drop.

### ISSUE THREAD

**Issue by ROHITHG77** [ItzMuri/ox_inventory-reskin#7]
When players drop items on floor some other prop is used to store the items like a wheelchair prop.

Framework - ESX

Version '2.40.2'

Just Drop Item.

A bag or a marker should show.

**Comment by ItzMuri** [comment]
![image](https://github.com/user-attachments/assets/0ceda827-13ea-4f54-b750-179b29c58ee6)

**Comment by ItzMuri** [comment]
```lua
# Disable drop markers and spawn a prop instead
setr inventory:dropprops true
 
# Set the default model used for drop props
setr inventory:dropmodel "prop_med_bag_01b"
```
